### ISSUE TITLE
implement pi type correctly

### ISSUE THREAD

**Issue by dannypsnl** [racket-tw/k#33]
To now, we still using a simulated pi type(of course make it weaker) that cannot be spread properly. I think now it's a good time to make it correct since it's all things' foundation.

**Comment by CYBAI** [comment]
As @dannypsnl discussed with me, we should do following steps to implement Pi type properly

1. Make universal level types
2. Confirm we can create universal types properly (e.g. a type in Type 0 exists in Type 1 but a type in Type 1 doesn't exist in Type 0)
3. After we have universal types, we can try to reuse them in Pi types

Refs:
[1]: https://sozeau.gitlabpages.inria.fr/www/research/publications/drafts/univpoly.pdf
[2]: https://ncatlab.org/homotopytypetheory/show/universe

**Comment by dannypsnl** [comment]
I think it's **a type in `Type0` exists in `Type1`**

`A : Type0` shows `A : Type1`

**Comment by dannypsnl** [comment]
We do hard coding for universe for now

**Comment by dannypsnl** [comment]
When we have 
```
data K
  c : K -> K
```

`c` should have type `Pi (_ : K) K`

**Comment by dannypsnl** [comment]
This is done and get usage now, let's treat universe level as a new issue
